import Head from "next/head"
import { useContext } from "react";
import { auth } from "../js/firebase.js";
import { Box } from "@chakra-ui/react";
import NavBar from "../components/NavBar";
import DashSection from "../components/DashSection";
import AuthRoute from "../authentication/AuthRoute";
import { AuthContext } from "../authentication/AuthContext.js";

const Home = () => {
    const { userInfo } = useContext(AuthContext)
    document.body.style.backgroundColor = "#221266";
    return (
        <AuthRoute>
            <Box>
                <Head>
                    <title>Dashboard</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
    
                <main style={{position: "relative"}}>
                    <NavBar auth={auth}/>
                    <Box />
                    <Box 
                        style={{
                            width: "90%", 
                            marginLeft: "auto", 
                            marginRight: "auto",
                        }}
                    >
                        <h1 
                            style={{
                            color: "#0ACF83", 
                            fontSize: "38px", 
                            fontWeight: "bold",
                            marginTop: "35px"
                            }}
                        >
                            Welcome, {userInfo.firstName}!
                        </h1>
                    
                        <DashSection uid={userInfo.uid} type={"Difference"}/>
                        <DashSection uid={userInfo.uid} type={"Expenses"}/>
                        <DashSection uid={userInfo.uid} type={"Income"}/>
                        <Box paddingBottom="80px"></Box>  
                    
                    </Box>
        
                </main>
            </Box>
        </AuthRoute>
    )
    
}

export default Home;

