import Head from "next/head"
import { useContext } from "react";
import { auth } from "../js/firebase.js";
import { 
    Box, 
    Grid, 
    GridItem, 
    useColorMode, 
    useColorModeValue, 
    Button, 
    IconButton,
    Text
} from "@chakra-ui/react";
import NavBar from "../components/NavBar2";
import { HamburgerIcon, MoonIcon } from '@chakra-ui/icons';
import DashSection from "../components/DashSection";
import MobileNavBar from "../components/MobileNavBar";
import AuthRoute from "../authentication/AuthRoute";
import { AuthContext } from "../authentication/AuthContext.js";

const Home2 = () => {
    const { userInfo } = useContext(AuthContext);

    const { colorMode, toggleColorMode } = useColorMode();

    const bgNav = useColorModeValue('white', 'gray.900');
    const bg = useColorModeValue('gray.200', 'gray.800');
    const navColor = useColorModeValue('gray.400', 'white');
    const color = useColorModeValue('#221266', 'white');
   
    return (
        <AuthRoute>
            <Box>
                <Head>
                    <title>Dashboard</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
    
                <main style={{position: "relative"}}>
                <Grid templateColumns='repeat(5, 1fr)' gap={0}>
                    <GridItem colSpan={1} display={{base: "none", md: "block"}} h="100vh" bg={bgNav}>
                        <NavBar bg={bgNav} color={navColor} colorMode={colorMode}/>
                    </GridItem>
                    <GridItem colSpan={{base: 5, md: 4}}  h="100vh" bg={bg} overflow="scroll">
                        <Box>
                            <Box 
                                float="right" 
                                marginTop="20px" 
                                marginRight="40px" 
                                display={{base: "none", md: "block"}}
                            >
                                <IconButton
                                    color={colorMode === 'light' ? 'gray.400' : 'white'}
                                    icon={<MoonIcon />}
                                    onClick={toggleColorMode}
                                    fontSize="20px"
                                    display={{base: "none", md: "block"}}
                                    
                                />
                                
                            </Box>
                            <MobileNavBar colorMode={colorMode} enableDark={toggleColorMode}/>
                        </Box>
                        <Box marginTop="65px" marginLeft="20px">
                            <Text fontSize='2xl' fontWeight="bold" color={color}>Dashboard</Text>

                            <Box marginTop="20px">
                                <DashSection uid={userInfo.uid} type={"Difference"}/>
                                <DashSection uid={userInfo.uid} type={"Expenses"}/>
                                <DashSection uid={userInfo.uid} type={"Income"}/>
                            </Box>

                        </Box>
                        
                        
                        
                    </GridItem>
                </Grid>
        
                </main>
            </Box>
        </AuthRoute>
    )
    
}

export default Home2;