import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Logo from "../public/images/logo-white.png";
import { useEffect } from "react";
import SignUpImage from "../public/images/signUpImage.png";
import { 
    Grid, 
    GridItem, 
    Button,   
    FormControl,
    FormLabel,
    FormErrorMessage,
    FormHelperText,
    Input, 
    Box,
    Center
} from "@chakra-ui/react"

const SignUp = () => {
    useEffect(()=>{
      
    },[]);
    return (
      <div>
        <Head>
          <title>Sign Up</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <main>
          <Grid templateColumns="repeat(3, 1fr)" w={{ base: "90%", sm: "98%", md: "100%" }} marginLeft="auto" marginRight="auto" gap={0}>
            <GridItem  
                colSpan={1} 
                display={{ base: "none", md: "block" }} 
                bg="#0ACF83" 
                h="100vh"
            >
                <Box display="flex" marginTop="20px">
                    <Box>
                        <Image src={Logo} width={120} height={45} style={{marginTop: "1px"}}/>
                    </Box>
                    
                    <h1 id="logo-text-white">Money Watcher</h1>
                </Box>
                <Box marginLeft="38px" marginTop="50px">
                    <p
                        style={{
                            fontWeight: "bold",
                            color: "white",
                            fontSize: "25px",
                            width: "73%"
                        }}
                    >
                        A few clicks away from starting your budgeting today
                    </p>
                    <Box
                        marginTop="35px"
                        marginLeft="-20px"
                    >
                        <Image src={SignUpImage} height={404} width={435} />
                    </Box>
                    
                </Box>
              
            </GridItem>
  
            <GridItem colSpan={{base: 3, md: 2}} bg = "white">
                <Box marginLeft={{base: "", sm: "130px"}}>
                    <Box marginTop={{base: "20px", sm: "80px"}}>
                        <h1 style={{fontSize: "25px", fontWeight: "bold"}}>Register</h1>
                        <p style={{fontSize: "20px", fontWeight: "bold", marginTop: "30px"}}>Manage your budget with ease</p>
                        <p style={{fontSize: "15px", fontWeight: "bold", marginTop: "10px", color: "grey", width: "70%"}}>Let"s get you started so that you can verify your account and begin budgeting today.</p>
                    </Box>
                    <form>
                        <Box marginTop="20px" width={{base: "100%", sm: "75%"}}>
                            <Box display="flex" width="100%">
                                <FormControl width = "49%">
                                    <FormLabel>First Name</FormLabel>
                                    <Input id="name" type="name" />
                                </FormControl>
                                <FormControl width = "49%" marginLeft = "2%">
                                    <FormLabel>Last Name</FormLabel>
                                    <Input id="name" type="name" />
                                </FormControl>
                            </Box>
                            <Box width="100%">
                                <FormControl marginTop="15px">
                                    <FormLabel>Email</FormLabel>
                                    <Input id="email" type="email" />
                                </FormControl>
                                
                                <FormControl marginTop="15px">
                                    <FormLabel>Password</FormLabel>
                                    <Input id="password" type="password" />
                                </FormControl>
                                <FormControl marginTop="15px">
                                    <FormLabel>Confirm Password</FormLabel>
                                    <Input id="re_password" type="password" />
                                </FormControl>
                                
                            </Box>
                        </Box>
                    </form>
                    <Button 
                        color="#FFFFFF"
                        bg="#0ACF83"
                        width={{base: "50%", md: "30%"}}
                        _hover={{ color: "#FFFFFF", bg: "#0ACF83"}}
                        marginTop="20px"
                    >
                        Create Account
                    </Button>
                    <Box fontSize="15px" fontWeight = "bold" marginTop ="20px" color="grey" >
                        <p>Already have an account? <Link href="/login"><a style={{color: "blue"}}>Log In</a></Link></p>
                    </Box>
                    

                </Box>
                
                
            </GridItem>
  
          </Grid>
          
          
            
          
        </main>
        
      
      </div>
    )
  }
  //templateColumns={{base: "repeat(3, 1fr)", sm: "repeat(2, 1fr)"}}
  export default SignUp;